// ingore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_name

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings for ExpidusOS's runtime
///
/// Regenerate bindings with `flutter pub run ffigen --config ffigen.yaml`.
///
class ExpidusRuntimeBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  ExpidusRuntimeBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  ExpidusRuntimeBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  bool has_wlroots() {
    return _has_wlroots();
  }

  late final _has_wlrootsPtr = _lookup<ffi.NativeFunction<ffi.Bool Function()>>(
      'expidus_runtime_compositor_has_wlroots');
  late final _has_wlroots = _has_wlrootsPtr.asFunction<bool Function()>();
}
