name: expidus_runtime_compositor
description: Compositing related section of the ExpidusOS runtime.
version: 0.0.1
homepage: https://expidusos.com

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.expidus.runtime.compositor
        pluginClass: Plugin
      linux:
        pluginClass: ExpidusRuntimeCompositorLinux
        fileName: platforms/impl/linux.dart
      macos:
        pluginClass: ExpidusRuntimeCompositorPlugin
      windows:
        pluginClass: ExpidusRuntimeCompositorPluginCApi
      web:
        pluginClass: ExpidusRuntimeCompositorWeb
        fileName: platforms/impl/web.dart
