set(EXPIDUS_RUNTIME_DIR "${CMAKE_CURRENT_LIST_DIR}/../")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${EXPIDUS_RUNTIME_DIR}/compositor/cmake")

function(apply_standard_settings TARGET)
  if(LINUX)
    target_compile_features(${TARGET} PUBLIC cxx_std_14)
    target_compile_options(${TARGET} PRIVATE -Wall -Werror)
    target_compile_options(${TARGET} PRIVATE "$<$<NOT:$<CONFIG:Debug>>:-O3>")
    target_compile_definitions(${TARGET} PRIVATE "$<$<NOT:$<CONFIG:Debug>>:NDEBUG>")
  elseif(WIN32)
    target_compile_features(${TARGET} PUBLIC cxx_std_17)
    target_compile_options(${TARGET} PRIVATE /W4 /WX /wd"4100")
    target_compile_options(${TARGET} PRIVATE /EHsc)
    target_compile_definitions(${TARGET} PRIVATE "_HAS_EXCEPTIONS=0")
    target_compile_definitions(${TARGET} PRIVATE "$<$<CONFIG:Debug>:_DEBUG>")
  endif()
endfunction()
